services:
  backend:
    build: ../backend
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONG_DB_URI=mongodb://mongodb:27017/visdb
    depends_on:
      - mongodb
    restart: always
  frontend:
    build: ../frontend
    ports:
      - 8080:80
    restart: always
  mongodb:
    image: mongo
    volumes:
      - dbdata:/data/db
    restart: always
volumes:
  dbdata: